setwd("C:/Users/vpatel/OneDrive - American Institutes for Research in the Behavioral Sciences/Desktop/datasciencecoursera/course 4")
library(data.table)
library(dplyr)
data <- read.table("./Week 1/household_power_consumption.txt", sep = ";", header = TRUE)
data$Date <- as.Date(data$Date,format = "%d/%m/%Y")
data_subset <- subset(data, data$Date == "2007-02-01" | data$Date == "2007-02-02")
