---
title: 'Reproducible Research: Peer Assessment 1'
author: "Chris"
date: "Friday, September 05, 2014"
output: html_document
---

Loading and preprocessing the data

```{r, echo = TRUE}
activity <- read.csv("activity.csv", colClasses = "character")
```

What is mean total number of steps taken per day?

```{r, echo = TRUE}
date <- levels(as.factor(activity[ , 2]))

dailysteps <- data.frame()

for(i in 1:length(date)) {
  isteps <- activity[activity[ , 2] == date[i], ]
  dailysteps[i, 1] <- sum(as.numeric(isteps[ , 1]))
  dailysteps[i, 2] <- date[i]
  }

## Show the histogram

hist(dailysteps[ , 1], main = "Everyday total number of steps", xlab = "Number of steps")

## Ignore the NAs
completeData <- dailysteps[complete.cases(dailysteps), ]

## Show the mean and median
mean(completeData[ , 1])
median(completeData[ , 1])
```

What is the average daily activity pattern?

```{r, echo = TRUE}
intervals <- levels(as.factor(activity[ , 3]))

activity[ , 3] <- as.numeric(activity[ , 3])

intervals5 <- as.numeric(intervals)
ll <- order(intervals5)
intervals5 <- intervals5[ll]

minintervals <- data.frame()
for(i in 1:length(intervals)) {
  minintervals[i, 1] <- intervals5[i]

  ## Calculate the mean of the steps in different intervals
  c <- activity[activity[ , 3] == intervals5[i], ]
  c <- c[complete.cases(c), ]
  
  minintervals[i, 2] <- mean(as.numeric(c[ , 1]))
  }

plot(minintervals, type = "l", xlab = "Interval", ylab = "Number of steps")

max <- max(minintervals[ , 2])
minintervals[minintervals[ , 2] == max, ]
```

Imputing missing values

```{r, echo = TRUE}
## Calculate the number of NAs
activity1 <- read.csv("activity.csv", colClasses = "character")

sum(is.na(activity1[ , 1]))    # Total number of missing values in the dataset

## Impute missing values using the mean steps of each intervals
n <- activity1[!complete.cases(activity1), ]
e <- as.numeric(rownames(n))

for(i in 1:length(e)) {
  f <- activity1[e[i], 3]
  activity1[e[i], 1] <- minintervals[minintervals[ , 1] == f, 2]
  }

dailystepsprime <- data.frame()

for(i in 1:length(date)) {
  istepsprime <- activity1[activity1[ , 2] == date[i], ]
  dailystepsprime[i, 1] <- sum(as.numeric(istepsprime[ , 1]))
  dailystepsprime[i, 2] <- date[i]
  }

## Show the new histogram and new mean and median
hist(dailystepsprime[ , 1], main = "Everyday total number of steps (revised)", xlab = "Number of steps")

mean(dailystepsprime[ , 1])
median(dailystepsprime[ , 1])

## The mean remains the same because I was using the mean value to replace the NAs. While the median became 10766
```

Are there differences in activity patterns between weekdays and weekends?

```{r, echo = TRUE}
## Generate the 3rd column showing weekdays and weekends
wd <- rep("weekday", 288*5)
we <- rep("weekend", 288*2)
week <- c(rep(c(wd, we), 8), wd)
activity2 <- cbind(activity, week)

## The new dataset would be like this
head(activity2)

## Use the same method to calculate the mean number of steps in intervals of weekdays and weekends
activitywd <- activity2[activity2[ , 4] == "weekday", ]
intervalswd <- levels(as.factor(activitywd[ , 3]))

activitywd[ , 3] <- as.numeric(activitywd[ , 3])

intervalswd5 <- as.numeric(intervalswd)
ll <- order(intervalswd5)
intervalswd5 <- intervalswd5[ll]

minintervalswd <- data.frame()
for(i in 1:length(intervalswd)) {
  minintervalswd[i, 1] <- mean(as.numeric(c[ , 1]))
  minintervalswd[i, 2] <- intervalswd5[i]
  
  c <- activitywd[activitywd[ , 3] == intervalswd5[i], ]
  c <- c[complete.cases(c), ]
  }

activitywe <- activity2[activity2[ , 4] == "weekend", ]
intervalswe <- levels(as.factor(activitywe[ , 3]))

activitywe[ , 3] <- as.numeric(activitywe[ , 3])

intervalswe5 <- as.numeric(intervalswe)
ll <- order(intervalswe5)
intervalswe5 <- intervalswe5[ll]

minintervalswe <- data.frame()
for(i in 1:length(intervalswe)) {
  minintervalswe[i, 1] <- mean(as.numeric(c[ , 1]))
  minintervalswe[i, 2] <- intervalswe5[i]
  
  c <- activitywe[activitywe[ , 3] == intervalswe5[i], ]
  c <- c[complete.cases(c), ]
  }

## Show the panel graph
wds <- cbind(minintervalswd, "weekday")
wes <- cbind(minintervalswe, "weekend")

colnames(wds) <- c("v1", "v2", "v3")
colnames(wes) <- c("v1", "v2", "v3")
dd <- rbind(wds, wes)
library(lattice)
xyplot(v1~ v2 | factor(v3), data = dd, type = "l", xlab = "Interval", ylab = "Number of steps", layout = c(1, 2))
```
