dat<-subset(read.delim(unz("exdata%2Fdata%2Fhousehold_power_consumption.zip","household_power_consumption.txt"),header=TRUE,sep=";"),Date=="1/2/2007"|Date=="2/2/2007")
DateTime <- as.POSIXlt(paste(dat$Date,dat$Time),format="%d/%m/%Y %H:%M:%S")
dat[,3:9] <- lapply(dat[,3:9],as.numeric)
png(filename = "Plot3.png")
with(dat,plot(DateTime,scale(Sub_metering_1,scale=FALSE)-min(scale(dat$Sub_metering_1,scale=FALSE)),type="l",ylab="Energy sub metering",xlab="",ylim=c(0,33.5)))
with(dat,lines(DateTime,scale(log(Sub_metering_2),scale =FALSE)-min(scale(log(Sub_metering_2),scale =FALSE)),col="red"))
with(dat,lines(DateTime,Sub_metering_3,col="blue"))
legend('topright', legend=c(names(dat[,7:9])),col=c('black','red','blue'),lty=1)
dev.off()