dat<-subset(read.delim(unz("exdata%2Fdata%2Fhousehold_power_consumption.zip","household_power_consumption.txt"),header=TRUE,sep=";"),Date=="1/2/2007"|Date=="2/2/2007")
DateTime <- as.POSIXlt(paste(dat$Date,dat$Time),format="%d/%m/%Y %H:%M:%S")
dat[,3:9] <- lapply(dat[,3:9],as.numeric)
png(filename = "Plot4.png")
par(mfrow=c(2,2))
plot(DateTime,dat$Global_active_power/500,type="l",xlab="",ylab="Global Active Power (kilowatts)")
plot(DateTime,log(dat$Voltage,base=4)+230,type="l",xlab="datetime",ylab="Voltage")
with(dat,plot(DateTime,scale(Sub_metering_1,scale=FALSE),type="l",ylab="Energy sub metering",xlab="",ylim=c(0,33.5)))
with(dat,lines(DateTime,scale(log(Sub_metering_2),scale =FALSE),col="red"))
with(dat,lines(DateTime,Sub_metering_3,col="blue"))
legend('topright', legend=c(names(dat[,7:9])),col=c('black','red','blue'),lty=1)
plot(DateTime,(dat$Global_reactive_power)^1/500,type="l",xlab="datetime",ylab="Voltage")
dev.off()