data <-read.csv("household_power_consumption.txt", header = TRUE, sep = ";",na.strings = "?")
data$Date<- as.Date(data$Date,format='%d/%m/%Y')
my_data <-subset(data, Date == "2007-2-1" | Date == "2007-2-2")
y<- transform(my_data, combine = paste(Date, Time, sep= " "))

y$combine<- strptime(y$combine, format = "%Y-%m-%d %H:%M:%S")
par(mfrow =c(2,2))
plot(y$combine,y$Global_active_power, type="l",  ylab=" Global Active Power",xlab="")
plot(y$combine,y$Voltage, type ="l",ylab = "Voltage",xlab = "")
plot(y$combine,y$Global_reactive_power,type = "l", ylab="Global Reactive Power",xlab = "Datatime" )
#ggplot(y, aes(y$combine)) + geom_line(aes(y =y$Sub_metering_1,colour ="y"))+ geom_line(aes(y =y$Sub_metering_2,colour ="z"))+ geom_line(aes(y =y$Sub_metering_3,colour ="r"))
plot(y$combine,y$Sub_metering_1, type = "l",col="red")
lines(y$combine,y$Sub_metering_2, type = "l", col = "green")
lines(y$combine,y$Sub_metering_3, type = "l",col="blue")
dev.copy(png,file="Plot4.png")
dev.off()