x<-read.table("household_power_consumption.txt",header = TRUE,sep = ";")
a<-x[x[,1]=="2/2/2007"]
b<-x[x[,1]=="1/2/2007",]
c<-rbind(b,a)
c[,3]<-as.numeric(as.character(c[,3]))
t<-paste(c[,1],c[,2])
newdt<-strptime(t,'%d/%m/%Y %H:%M:%S')
par(mfrow=c(2,2))
plot(newdt,c[,3],lwd=1,xlab="",ylab="Global Active Power(kilowatts)",main="",type="l",lty=1)
plot(newdt,as.numeric(as.character(c[,5])),lwd=1,xlab="datatime",ylab="Voltage",main="",type="l",lty=1)
plot(newdt,as.numeric(as.character(c[,7])),lwd=1,xlab="",ylab="Energy sub metering",main="",type="l",lty=1)
lines(newdt,as.numeric(as.character(c[,8])),col="red",lwd=1,xlab="",ylab="Energy sub metering",main="",type="l",lty=1)
lines(newdt,as.numeric(as.character(c[,9])),col="blue",lwd=1,xlab="",ylab="Energy sub metering",main="",type="l",lty=1)
legend("topright",c("Sub_metering_1","Sub_metering_2","Sub_metering_3"),lty=1,col=c("black","red","blue"),bty = 'n')
plot(newdt,as.numeric(as.character(c[,4])),lwd=1,xlab="datatime",ylab="Global_reactive_power",main="",type="l",lty=1)
dev.copy(png,file="plot4.png",width=480,height=480)
dev.off()