##plot4
data<-read.csv("household_power_consumption.txt", sep = ";",stringsAsFactors=FALSE,na.strings = "?")##read all data
newdata <- data[which(data$Date=="1/2/2007" | data$Date =="2/2/2007" | data$Date =="3/2/2007"), ]##subest data by date
newdata$Date<- as.POSIXct(newdata$Date,format='%d/%m/%Y')
newdata$day <- weekdays(newdata$Date,abbreviate = TRUE)
png(filename = "plot4.png",width = 480, height = 480)
par(mfrow=c(2,2))
time<-seq(1,2881)
plot(time,newdata$Global_active_power[time], type = "l",xaxt = "n",xlab = "", ylab = "Global Active Power")
axis(1, c(1,1441,2881),c(newdata$day[1],newdata$day[1441],newdata$day[2881]))
plot(time,newdata$Voltage[time], type = "l",xaxt = "n",xlab = "datetime", ylab = "Voltage")
axis(1, c(1,1441,2881),c(newdata$day[1],newdata$day[1441],newdata$day[2881]))
plot(time,newdata$Sub_metering_1[time], type = "l",xaxt = "n",xlab = "", ylab = "Energy sub metering")
lines(newdata$Sub_metering_2[time], col = "red")
lines(newdata$Sub_metering_3[time], col = "blue")
legend("topright", cex=0.95,c("Sub_metering_1","Sub_metering_2","Sub_metering_3"),lty=c(1,1,1),col=c("black","red","blue"),bty="n")
axis(1, c(1,1441,2881),c(newdata$day[1],newdata$day[1441],newdata$day[2881]))
plot(time,newdata$Global_reactive_power[time], lwd = .25,type = "l",xaxt = "n",xlab = "datetime", ylab = "Global_reactive_power")
axis(1, c(1,1441,2881),c(newdata$day[1],newdata$day[1441],newdata$day[2881]))
dev.off()