urldr<-"https://d396qusza40orc.cloudfront.net/exdata%2Fdata%2Fhousehold_power_consumption.zip"
download.file(urldr,"household_power_consumption.zip")
unzip("household_power_consumption.zip")
dataEAPA<-read.table("household_power_consumption.txt",header=TRUE, sep=";", stringsAsFactors=FALSE,dec=".")
datEA<-dataEAPA[dataEAPA$Date %in% c("1/2/2007","2/2/2007"),]
head(datEA)
class(datEA$Sub_metering_1)
class(datEA$Sub_metering_2)
class(datEA$Sub_metering_3)
SM1<-as.numeric(datEA$Sub_metering_1)
SM2<-as.numeric(datEA$Sub_metering_2)
SM3<-as.numeric(datEA$Sub_metering_3)
Fechas<-as.POSIXct(paste(datEA$Date,datEA$Time,sep=""), format="%d/%m/%Y %H:%M:%S")
png("Plot3.png",width=480,height=480)
plot(Fechas,SM1,type="l",ylab="Energy sub metering",xlab="")
lines(Fechas,SM2,col="red")
lines(Fechas,SM3,col="blue")
legend("topright",lwd=1,lty=1,col=c("black","red","blue"),legend=c("Sub_metering_1","Sub_metering_2","Sub_metering_3"))
dev.off()
