png("plot3_png",width=480,height=480)
data<-read.table("household_power_consumption.txt", skip=66637,nrow=2880,head=FALSE,sep=";",col.names=c("Date","Time","Global_active_power","Global_reactive_power","Voltage","Global_intensity","Sub_metering_1","Sub_metering_2","Sub_metering_3"))
data$DateTime<-paste(data[,1], data[,2])
data$datetime<-as.POSIXct(strptime(data[,10], "%d/%m/%Y %H:%M:%S"))
with(data,plot(data[,11],data[,7],type="n",xlab="",ylab="Energy sub metering"))
with(data,points(data[,11],data[,7],col="black",type="l"))
with(data,points(data[,11],data[,8],col="red",type="l"))
with(data,points(data[,11],data[,9],col="blue",type="l"))
legend("topright",lty=1,col=c("black","red","blue"),legend=c("Sub_metering_1","Sub_metering_2","Sub_metering_3") )
dev.off()