png(filename="plot4.png",width = 480,height = 480)
par(mfrow = c(2,2))
with(data,hist(Global_active_power,col="red",xlab="Global Active Power (kilowatts)",main=""))
plot(data$DateTime,data$Voltage,pch=NA_integer_,xlab="datetime",ylab="Voltage")
lines(data$DateTime,data$Voltage)
with(data,plot(data$DateTime,data$Sub_metering_1,pch=NA_integer_, ylab = "Energy sub metering",xlab=""))
lines(data$DateTime,data$Sub_metering_1)
lines(data$DateTime,data$Sub_metering_2,col="red")
lines(data$DateTime,data$Sub_metering_3,col="blue")
legend('topright', legend=c('Sub_metering_1', 'Sub_metering_2', 'Sub_metering_3'), lwd='1', bty="n",col=c('black', 'red', 'blue'),border = 0)
with(data,plot(DateTime,Global_reactive_power,type="s"))
dev.off()
