setwd("/Users/sisovina/github/ExData_Plotting1")
allrows <- read.table("household_power_consumption.txt", header = TRUE, sep = ";", stringsAsFactors = FALSE, na.strings = "?")
subdata <- subset(allrows, Date == "1/2/2007" | Date == "2/2/2007")
rm(allrows)
datetime <- strptime(paste(subdata$Date, subdata$Time), format = "%d/%m/%Y %H:%M:%S")
png(filename = "plot3.png", width = 480, height = 480)
plot(datetime, subdata$Sub_metering_1, type = "l", ylab = "Energy sub metering", xlab = "")
lines(datetime, subdata$Sub_metering_2, col = "red")
lines(datetime, subdata$Sub_metering_3, col = "blue")
legend("topright", c("Sub_metering_1","Sub_metering_2","Sub_metering_3"), col = c("black","red","blue"), lty = 1)
dev.off()