bigData <- read.table("household_power_consumption.txt", header=TRUE, sep=";", stringsAsFactors=FALSE)
data2use <- bigData[bigData$Date %in% c("1/2/2007","2/2/2007"),]
rm(bigData)
datetime <- strptime(paste(data2use$Date, data2use$Time, sep=" "), "%d/%m/%Y %H:%M:%S")
png("plot4.png", width=480, height=480)
par(mfrow=c(2,2))
plot(datetime, as.numeric(data2use$Global_active_power), type="l", xlab="", ylab="Global Active Power")
plot(datetime, as.numeric(data2use$Voltage), type="l", xlab="datetime", ylab="Voltage")
plot(datetime, as.numeric(data2use$Sub_metering_1), type="l", xlab="", ylab="Energy sub metering")
lines(datetime, as.numeric(data2use$Sub_metering_2), type="l", col="red")
lines(datetime, as.numeric(data2use$Sub_metering_3), type="l", col="blue")
legend("topright", c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"), lty=1, lwd=2, col=c("black", "red", "blue"))
plot(datetime, as.numeric(data2use$Global_reactive_power), type="l", xlab="datetime", ylab="Global_reactive_power")
dev.off()