data_set <- read.table("./data/household_power_consumption.txt", header=TRUE, sep=";", stringsAsFactors=FALSE)
mini_data_set <- data_set[data_set$Date %in% c("1/2/2007","2/2/2007") ,]

date_time <- strptime(paste(mini_data_set$Date, mini_data_set$Time, sep=" "), "%d/%m/%Y %H:%M:%S")
global_Active_Power <- as.numeric(mini_data_set$Global_active_power)
global_Reactive_Power <- as.numeric(mini_data_set$Global_reactive_power)
voltage <- as.numeric(mini_data_set$Voltage)
sub_Metering_1 <- as.numeric(mini_data_set$Sub_metering_1)
sub_Metering_2 <- as.numeric(mini_data_set$Sub_metering_2)
sub_Metering_3 <- as.numeric(mini_data_set$Sub_metering_3)
png("plot4.png", width=480, height=480)
par(mfrow = c(2, 2))
plot(date_time, global_Active_Power, type="l", xlab="", ylab="Global Active Power", cex=0.2)
plot(date_time, voltage, type="l", xlab="datetime", ylab="Voltage")
plot(date_time, sub_Metering_1, type="l", ylab="Energy Submetering", xlab="")
lines(date_time, sub_Metering_2, type="l", col="red")
lines(date_time, sub_Metering_3, type="l", col="blue")
legend("topright", c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"), lty=, lwd=2.5, col=c("black", "red", "blue"), bty="o")
plot(date_time, global_Reactive_Power, type="l", xlab="datetime", ylab="Global_reactive_power")
dev.off()
