setwd("C:/Users/brecre01/Documents/Coursera")
mydata <- read.csv("household_power_consumption.txt", header=TRUE, sep=';', check.names=FALSE, na.strings="?", stringsAsFactors=FALSE, comment.char="", quote='\"')
mydata$Date <- as.Date(mydata$Date, format="%d/%m/%Y")
datasm <- subset(mydata, subset=(Date >= "2007-02-01" & Date < "2007-02-03"))
datetimeonly <- paste(as.Date(datasm$Date), datasm$Time)
datasm$Datetime <- as.POSIXct(datetimeonly)
par(mfcol=c(2,2))
plot(datasm$Datetime, datasm$Global_active_power, type= "l", lwd=1, ylab= "Global Active Power (kilowatts)", xlab="")
plot(datasm$Datetime, datasm$Sub_metering_1, type="l", ylab= "Energy sub metering", xlab="")
lines(datasm$Datetime, datasm$Sub_metering_2, type="l", col="red")
lines(datasm$Datetime, datasm$Sub_metering_3, type="l", col="blue")
legend("topright", c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"), lty=1, bty="n", col=c("black", "red", "blue"))
plot(datasm$Datetime, datasm$Voltage, type="l", xlab="datetime", ylab="Voltage")
plot(datasm$Datetime, datasm$Global_reactive_power, type="l", xlab="datetime", ylab="Global_reactive_power")
dev.copy(png, file="plot4.png", height=480, width=480)
dev.off()
