h_p_c <- read.table(file = "household_power_consumption.txt", sep = ";", header = TRUE,stringsAsFactors = FALSE)
h_p_c <- unite(h_p_c, "DateTime", c("Date", "Time"), sep = " ")
h_p_c$DateTime <- strptime(h_p_c$DateTime, format = "%d/%m/%Y %H:%M:%S")
h_p_c <- na.omit(h_p_c)
h_p_c$DateTime <- as.POSIXct(h_p_c$DateTime)
h_p_c <- filter(h_p_c, h_p_c$DateTime > "2007-02-01" & h_p_c$DateTime < "2007-02-03")
png(file = "plot1.png", width = 480, height = 480)
hist(as.numeric(h_p_c$Global_active_power), col = "red", main = "Global Active Power", xlab = "Global Active Power(KiloWatt)")
dev.off()
