---
title: "Exploratory Data Analysis Project1"
author: "Wahsabii Neandertal"
date: "Saturday, March 07, 2015"
output: html_document
---
### Purpose.
To produce four plots (1) Global Active Power (2) Voltage (3) Energy Sub Metering and (4) Global Reactive Power from individual household electric power consumption from 1-2 February 2007. 

### Input  
A dataset from the UC Irvine Machine Learning Repository
[Electric power consumption] (https://d396qusza40orc.cloudfront.net/exdata%2Fdata%2Fhousehold_power_consumption.zip) 


#### Variable Descriptions.
Measurements of electric power consumption in one household with a one-minute sampling rate over a period of almost 4 years with three different electrical quantities and some sub-metering values.

The following descriptions of the 9 variables in the dataset are taken from the UCI web site:

Date: Date in format dd/mm/yyyy  
Time: time in format hh:mm:ss  
Global_active_power: household global minute-averaged active power (in kilowatt)  
Global_reactive_power: household global minute-averaged reactive power (in kilowatt)  
Voltage: minute-averaged voltage (in volt)  
Global_intensity: household global minute-averaged current intensity (in ampere)  
Sub_metering_1: energy sub-metering No. 1 (in watt-hour of active energy). It corresponds to the kitchen, containing mainly a dishwasher, an oven and a microwave (hot plates are not electric but gas powered).  
Sub_metering_2: energy sub-metering No. 2 (in watt-hour of active energy). It corresponds to the laundry room, containing a washing-machine, a tumble-drier, a refrigerator and a light.  
Sub_metering_3: energy sub-metering No. 3 (in watt-hour of active energy). It corresponds to an electric water-heater and an air-conditioner.  

### Output
Output of the four R scripts plot1.R, plot2.R, plot3.R, and plot4.R is four graphical plots named plot1.png, plot2.png, plot3.png, and plot4.png respectively. 






