data <- read.table("household_power_consumption.txt", sep=";", header=TRUE)
wdata <- subset(data, Date %in% c("1/2/2007","2/2/2007"))
png("plot2.png", width=480, height=480, units="px")
hist(as.numeric(as.character(wdata$Global_active_power)), col="red", main="Global Active Power", xlab="Global Active Power (kilowatts)")
dev.off()
