a<-read.table("household_power_consumption.txt",sep=";",header=TRUE)
a$Date<-as.Date(a$Date,format="%d/%m/%Y")
b1<-subset(a,Date=="2007-02-01")
b2<-subset(a,Date=="2007-02-02")
b<-rbind(b1,b2)
b$Sub_metering_1<-as.numeric(as.character(b$Sub_metering_1))
b$Sub_metering_2<-as.numeric(as.character(b$Sub_metering_2))
b$Sub_metering_3<-as.numeric(as.character(b$Sub_metering_3))
b$Global_active_power<-as.numeric(as.character(b$Global_active_power))
b$DateTime<-paste(b$Date,b$Time)
b$DateTime<-strptime(b$DateTime,"%Y-%m-%d %H:%M:%S")
par(mar=c(4,4,2,1))
plot(b$DateTime,b$Sub_metering_1,type="l",ylab="Energy Sub Metering",xlab="")
lines(b$DateTime,b$Sub_metering_3,col="blue")
lines(b$DateTime,b$Sub_metering_2,col="red")
legend("topright",c("Sub_metering_1","Sub_metering_2","Sub_metering_3"),lty=c(1,1,1),col=c("black","red","blue"))