a<-read.table("household_power_consumption.txt",sep=";",header=TRUE)
a$Date<-as.Date(a$Date,format="%d/%m/%Y")
b1<-subset(a,Date=="2007-02-01")
b2<-subset(a,Date=="2007-02-02")
b<-rbind(b1,b2)
b$Global_active_power<-as.numeric(as.character(b$Global_active_power))
b$DateTime<-paste(b$Date,b$Time)
b$DateTime<-strptime(b$DateTime,"%Y-%m-%d %H:%M:%S")
par(mar=c(4,4,2,1))
plot(b$DateTime,b$Global_active_power,type="l",ylab="Global Active Power (Kilowatts)",xlab="")
