a<-read.table("household_power_consumption.txt",sep=";",header=TRUE)
a$Date<-as.Date(a$Date,format="%d/%m/%Y")
b1<-subset(a,Date=="2007-02-01")
b2<-subset(a,Date=="2007-02-02")
b<-rbind(b1,b2)
b$Sub_metering_1<-as.numeric(as.character(b$Sub_metering_1))
b$Sub_metering_2<-as.numeric(as.character(b$Sub_metering_2))
b$Sub_metering_3<-as.numeric(as.character(b$Sub_metering_3))
b$Global_reactive_power<-as.numeric(as.character(b$Global_reactive_power))
b$Voltage<-as.numeric(as.character(b$Voltage))
b$Global_active_power<-as.numeric(as.character(b$Global_active_power))
b$DateTime<-paste(b$Date,b$Time)
b$DateTime<-strptime(b$DateTime,"%Y-%m-%d %H:%M:%S")
par(mar=c(4,4,1,1))
par(mfrow=c(2,2))
plot(b$DateTime,b$Global_active_power,type="l",ylab="Global Active Power",xlab="",cex.lab=.5,cex.axis=.75)
plot(b$DateTime,b$Voltage,type="l",ylab="Voltage",xlab="datetime",cex.lab=.5,cex.axis=.75)
plot(b$DateTime,b$Sub_metering_1,type="l",ylab="Energy Sub Metering",xlab="",cex.lab=.5,cex.axis=.75)
lines(b$DateTime,b$Sub_metering_3,col="blue")
lines(b$DateTime,b$Sub_metering_2,col="red")
legend("topright",c("Sub_metering_1","Sub_metering_2","Sub_metering_3"),lty=c(1,1,1),col=c("black","red","blue"),cex=c(.5,.5,.5))
plot(b$DateTime,b$Global_reactive_power,type="l",ylab="Global_reactive_power",xlab="datetime",cex.lab=.5,cex.axis=.75)