table<-read.table("./household_power_consumption.txt", header = TRUE, sep = ";")
table$Date<-as.Date(table$Date, format = "%d/%m/%Y")
subset<-subset(table, table$Date == as.Date("2007-02-01") | table$Date == as.Date("2007-02-02"))
png(filename="plot3.png", width = 480, height = 480)
plot(as.numeric(as.character(subset$Sub_metering_1)), type = "l", ylab = "Energy sub metering", xlab = "", xaxt='n', yaxt = 'n')
lines(as.numeric(as.character(subset$Sub_metering_2)), col = "red")
lines(as.numeric(as.character(subset$Sub_metering_3)), col = "blue")
axis(side = 1, at=seq(0, 2880, 1440), labels = c("Thu", "Fri", "Sat"))
axis(side=2, at=seq(0,30, 5), labels = seq(0,30, 5))
legend("topright",lwd = 1 , col = c("black", "red", "blue"), legend = c("sub_metering_1", "sub_metering_2", "sub_metering_3"))
dev.off()
